'use strict';

module.exports = Object.freeze({
    ATTRIBUTE_TYPE: {
        0: "Uninitialized",
        1: "Uint32",
        2: "Int32",
        3: "Float",
        4: "String",
        5: "Vector2",
        6: "EntityType",
        7: "ArrayVector2",
        8: "ArrayUint32",
        9: "Uint16",
        10: "Uint8",
        11: "Int16",
        12: "Int8",
        13: "Uint64",
        14: "Int64",
        15: "Double",
        Uninitialized: 0,
        Uint32: 1,
        Int32: 2,
        Float: 3,
        String: 4,
        Vector2: 5,
        EntityType: 6,
        ArrayVector2: 7,
        ArrayUint32: 8,
        "Uint16": 9,
        "Uint8": 10,
        "Int16": 11,
        "Int8": 12,
        "Uint64": 13,
        "Int64": 14,
        "Double": 15
    },
    PARAMETER_TYPE: {
        Uint32: 0,
        Int32: 1,
        Float: 2,
        String: 3,
        Uint64: 4,
        Int64: 5,
        0: 'Uint32',
        1: 'Int32',
        2: 'Float',
        3: 'String',
        4: 'Uint64',
        5: 'Int64'
    },
    PACKET: {
        ENTITY_UPDATE: 0,
        PLAYER_COUNTER_UPDATE: 1,
        SET_WORLD_DIMENSIONS: 2,
        INPUT: 3,
        ENTER_WORLD: 4,
        PRE_ENTER_WORLD: 5,
        ENTER_WORLD2: 6,
        PING: 7,
        RPC: 9,
        0: 'PACKET_ENTITY_UPDATE',
        1: 'PACKET_PLAYER_COUNTER_UPDATE',
        2: 'PACKET_SET_WORLD_DIMENSIONS',
        3: 'PACKET_INPUT',
        4: 'PACKET_ENTER_WORLD',
        5: 'PACKET_PRE_ENTER_WORLD',
        6: 'PACKET_ENTER_WORLD2',
        7: 'PACKET_PING',
        9: 'PACKET_RPC'
    },
    LOGGING: {
        NO_PACKET: ['debug', 'info', 'warn', 'error'],
        ALL: ['debug', 'info', 'warn', 'error', 'incoming', 'outgoing'],
        NONE: []
    }
});